// Code generated from patches/. DO NOT EDIT.

// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.newinliner

package goexperiment

const NewInliner = true
const NewInlinerInt = 1
