// Code generated from patches/. DO NOT EDIT.

// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.runtimesecret

package goexperiment

const RuntimeSecret = true
const RuntimeSecretInt = 1
