// Code generated from patches/. DO NOT EDIT.

// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.cgocheck2

package goexperiment

const CgoCheck2 = false
const CgoCheck2Int = 0
