// Code generated from patches/. DO NOT EDIT.

// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.goroutineleakprofile

package goexperiment

const GoroutineLeakProfile = false
const GoroutineLeakProfileInt = 0
