// Code generated from patches/. DO NOT EDIT.

// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.regabiargs

package goexperiment

const RegabiArgs = false
const RegabiArgsInt = 0
