// Code generated from patches/. DO NOT EDIT.

// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.boringcrypto

package goexperiment

const BoringCrypto = true
const BoringCryptoInt = 1
