// Code generated from patches/. DO NOT EDIT.

// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.fieldtrack

package goexperiment

const FieldTrack = false
const FieldTrackInt = 0
